### PR TITLE
Refactor into slack directory and add a data resource for users.

### PR DESCRIPTION
**Pull request by joestump**

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
@joestump lol this is a huge PR ...

**Comment by joestump** [comment]
@cornfeedhobo haha, yeah, I should break this up into a couple of PRs. All that's really in the PR is removing the `vendor` folder, moving the provider into a `slack` directory and a single data provider for users here: https://github.com/sfdc-pcg/terraform-provider-slack/blob/fcff535dd14b167f035303b11d5b5a7890edc003/slack/data_source_slack_user.go

The provider itself didn't do much of anything. The bot resource just queried for Slack users and, sadly, you can't actually create bots via the Slack API.

**Comment by cornfeedhobo** [comment]
@joestump bummer. managing bot users was something I was wanting to roll up my sleeves on once time allowed. Thanks for working on this. I'll be keeping an eye out for future development.

**Comment by rngtng** [comment]
good to see progress for this provider. how do we move forward here? will you split the PR or is it good as this and let's merge?

/cc @nicholasjackson

**Comment by nicholasjackson** [comment]
I totally missed, this, I originally created the repo as I wanted a way to create but users and integrations but the Slack API did not allow this, I have merged as I am positive https://github.com/nicholasjackson/terraform-provider-slack/commit/f08b927b63e70209ef76cb6056f8826e828141a9 is better than my original code

**Comment by rngtng** [comment]
cool thank. I'd like to setup user for slack too, especially creating user groups - bummer this doesn't work :(

**Pull request merged**
